name: build

on: [push, pull_request]

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run sh-checker for bash
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
          SHELLCHECK_OPTS: -s bash
      - name: Run sh-checker for sh
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
          SHELLCHECK_OPTS: -s sh
      - name: Run sh-checker for dash
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
          SHELLCHECK_OPTS: -s dash
      - name: Run sh-checker for ksh
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
          SHELLCHECK_OPTS: -s ksh
